name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y pip
      - run: pip install mkdocs mkdocs-get-deps mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-material-extensions mkdocs-minify-plugin mkdocs-rss-plugin
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: make
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './site/'
      - id: deployment
        uses: actions/deploy-pages@v4
